import type { Pathway, Project, Resource } from "@/types/content";

export const pathways: Pathway[] = [
  { id: "policy", number: 1, title: "National seed policy and regulatory framework", summary: "Create an enabling and locally appropriate foundation for seed-sector development.", priorities: ["Wider consultation on seed policy, law and regulation", "Technical working group under the Seed Hub", "Practical standard operating procedures"], status: "published" },
  { id: "coordination", number: 2, title: "Coordination, digital inclusion and partnerships", summary: "Build the relationships and information infrastructure needed for coherent action.", priorities: ["Seed Hub events at national and state levels", "A digital portal for knowledge and activities", "Investment in coordination and professional capacity"], status: "published" },
  { id: "relief", number: 3, title: "From seed relief to seed-sector development", summary: "Connect humanitarian response with local production and longer-term market development.", priorities: ["Link market-based interventions with local seed production", "Strengthen informal seed systems", "Develop rural agro-dealer networks"], status: "published" },
  { id: "farmer-systems", number: 4, title: "Farmer-based seed systems", summary: "Support local seed producers, farmer organizations and community seed banks.", priorities: ["Professional local seed businesses", "Decentralized quality assurance services", "Access to information, finance and suitable varieties"], status: "published" },
  { id: "private-sector", number: 5, title: "Private seed-sector development", summary: "Create a more transparent and enabling environment for responsible seed enterprise.", priorities: ["Innovative finance mechanisms", "Reliable access to foundation seed", "Effective and consistent certification"], status: "published" },
  { id: "quality", number: 6, title: "Decentralized seed quality assurance", summary: "Bring credible quality services closer to producers and farmers.", priorities: ["Validate a decentralized system", "Develop technical and laboratory capacity", "Agree roles, standards and service arrangements"], status: "published" },
  { id: "genebanks", number: 7, title: "A national genebank linked to community seed banks", summary: "Conserve and use crop diversity through connected national and community institutions.", priorities: ["Appoint a responsible institution and focal point", "Mobilize financial and human resources", "Collect, characterize, evaluate and use germplasm"], status: "published" },
  { id: "breeding", number: 8, title: "Crop breeding and access to new varieties", summary: "Strengthen research capacity and farmers’ access to well-adapted varieties.", priorities: ["Strengthen national agricultural research", "Build human and physical research capacity", "Expand regional technical and material cooperation"], status: "published" },
  { id: "egs", number: 9, title: "Public–private foundation seed production", summary: "Create dependable early-generation seed supply through clear operational partnerships.", priorities: ["Formalize an EGS operational framework", "Forecast demand and coordinate production", "Develop production and quality guidelines"], status: "published" },
  { id: "institutions", number: 10, title: "Capacity of government and public institutes", summary: "Build the people, infrastructure and institutions needed to sustain transformation.", priorities: ["Rehabilitate research facilities", "Update seed-related education and training", "Mobilize alternative resources for research"], status: "published" },
];

export const bsfProject: Project = {
  slug: "bsf",
  shortName: "BSF project",
  title: "Plant diversity, local value chains and shared knowledge",
  summary: "The regional BSF project sub-hub brings together its partners, activities, news, publications and resources in one shared space.",
  status: "provisional",
  workstreams: [
    { number: 1, title: "Adapted PGRFA managed or improved with farmers’ participation", description: "Activities support the conservation, management and improvement of adapted plant genetic resources through meaningful farmer participation." },
    { number: 2, title: "Enhanced local value chains to improve the production and consumption of adapted PGRFA", description: "Activities connect crop diversity with production, processing, markets and consumption through stronger local value chains." },
    { number: 3, title: "Mechanisms strengthened to enhance the sharing of PGRFA data, materials and knowledge", description: "Activities improve how project partners and wider seed-system actors exchange materials, information, evidence and practical learning." },
  ],
};

export const resources: Resource[] = [
  { id: "call-to-action", title: "Call to action: priorities and partnerships for South Sudan’s seed sector", type: "Policy brief", year: 2022, summary: "The evidence and stakeholder dialogue behind the ten pathways for transformation.", topics: ["Policy", "Coordination", "Resilience"], countries: ["South Sudan"], url: "https://arnab1811.github.io/webtest/call.pdf", external: true, status: "published" },
  { id: "fao-bsf", title: "The International Treaty’s Benefit-sharing Fund", type: "External resource", year: "Accessed 2026", summary: "FAO’s official overview of the Fund, its place in the Treaty’s Funding Strategy and its project cycles.", topics: ["PGRFA", "Benefit sharing", "International Treaty"], countries: ["Global"], url: "https://www.fao.org/plant-treaty/areas-of-work/benefit-sharing-fund/bsf-overview/en/", external: true, status: "published" },
  { id: "fao-glis", title: "Global Information System for PGRFA (GLIS)", type: "External resource", year: "Accessed 2026", summary: "The Treaty’s global entry point for information and knowledge supporting conservation, management and use of PGRFA.", topics: ["PGRFA", "Data", "Knowledge exchange"], countries: ["Global"], url: "https://glis.fao.org/", external: true, status: "published" },
  { id: "uganda-genebank", title: "Uganda National Genebank profile", type: "External resource", year: "Accessed 2026", summary: "Crop Trust profile of the NARO-PGRC genebank, its mission, crop collections and links with community seed banks.", topics: ["Genebanks", "Conservation", "Community seed banks"], countries: ["Uganda"], url: "https://bold.croptrust.org/genebanks/uganda/", external: true, status: "published" },
  { id: "uoj-research", title: "University of Juba research publications repository", type: "External resource", year: "Accessed 2026", summary: "The University’s public portal for research publications, projects and collaboration across its schools and institutes.", topics: ["Research", "Publications", "Higher education"], countries: ["South Sudan"], url: "https://research.uoj.edu.ss/", external: true, status: "published" },
  { id: "mafs-research", title: "Directorate of Agricultural Research", type: "External resource", year: "Accessed 2026", summary: "The Directorate’s official place within South Sudan’s Ministry of Agriculture and Food Security web structure.", topics: ["Agricultural research", "Public institutions"], countries: ["South Sudan"], url: "https://mafs.gov.ss/agricultural-research/", external: true, status: "published" },
  { id: "issd-africa", title: "ISSD Africa community of practice", type: "External resource", year: "Accessed 2026", summary: "A regional community of practice supporting seed-sector transformation and innovation, with publications and action-learning projects.", topics: ["Seed systems", "Quality seed", "Regional learning"], countries: ["Africa"], url: "https://issdafrica.org/", external: true, status: "published" },
];

export const organisations = [
  { slug: "uoj", name: "University of Juba", role: "Higher education and research", location: "South Sudan", summary: "Established in 1975, the University combines teaching, research, innovation and service to the community; its public repository includes natural-resources research.", website: "https://uoj.edu.ss/" },
  { slug: "mafs", name: "Ministry of Agriculture and Food Security", role: "National public institution", location: "South Sudan", summary: "The national ministry’s public structure covers agriculture, food security, research, plant protection, extension and related services.", website: "https://mafs.gov.ss/" },
  { slug: "dar", name: "Directorate of Agricultural Research", role: "Agricultural research", location: "South Sudan", summary: "The Ministry’s official website lists the Directorate within its Agriculture and Food Security sector.", website: "https://mafs.gov.ss/agricultural-research/" },
  { slug: "naro", name: "NARO Plant Genetic Resources Centre", role: "PGRFA and national genebank", location: "Uganda", summary: "The Centre conserves, manages and supports sustainable use of Uganda’s PGRFA; the Uganda National Genebank is one of its components.", website: "https://www.croptrust.org/knowledge-hub/partners/genebank/national-agricultural-research-organization-naro/" },
  { slug: "fao", name: "Food and Agriculture Organization", role: "Treaty and global information", location: "Global", summary: "FAO hosts the International Treaty’s Benefit-sharing Fund and its Global Information System for PGRFA.", website: "https://www.fao.org/plant-treaty/en/" },
  { slug: "wur", name: "Wageningen University & Research", role: "Research and knowledge", location: "Netherlands", summary: "WUR combines education and research on climate, biodiversity, food and nutrition, and the living environment.", website: "https://www.wur.nl/" },
  { slug: "alliance", name: "Alliance of Bioversity International and CIAT", role: "Agrobiodiversity and food systems", location: "Regional", summary: "A CGIAR Research Centre delivering research-based solutions that harness agricultural biodiversity and transform food systems.", website: "https://alliancebioversityciat.org/" },
  { slug: "issd", name: "ISSD Africa", role: "Seed-systems community of practice", location: "Africa", summary: "An international community of practice supporting seed-sector transformation and innovation and improved farmer access to quality seed.", website: "https://issdafrica.org/" },
];
